 var products = [
    {"id":0,"Image":"no1.jpg"},
    {"id":1,"Image":"Assets/inerwood prod/if-sofa1.jpg","Brand":"Interwood Hester","Name":"Hester","Price":"PKR 117,528","Color":"black",},
    {"id":2,"Image":"Assets/inerwood prod/if-sofa2.png","Brand":"Interwood Sofa Kessel","Name":"Sofa Kessel","Price":"PKR 202,852","Color":"gray",},
    {"id":3,"Image":"Assets/inerwood prod/if-bed1.jpg","Brand":"Interwood Fresco","Name":"Freasco","Price":"PKR 405,123","Color":"Light Brown",},
    {"id":4,"Image":"Assets/inerwood prod/if-bed3.jpg","Brand":"Interwood Chelsea","Name":"Chelsea","Price":"PKR 117,528","Color":"gray",},
    {"id":5,"Image":"Assets/inerwood prod/if-studyandoffice1.jpg","Brand":"Interwood Study Table","Name":"Study Table","Price":"PKR 9,130","Color":"Willow Red",},
    {"id":6,"Image":"Assets/inerwood prod/if-studyandoffice3.jpg","Brand":"Interwood Study Chair","Name":"Study Chair","Price":"PKR 23,550","Color":"Black",},
    {"id":7,"Image":"Assets/inerwood prod/if-chair1.jpg","Brand":"Interwood Dining Chair Willa","Name":"Dining Chair Willa","Price":"PKR 8,632","Color":"all",},
    {"id":8,"Image":"Assets/inerwood prod/if-chair3.jpg","Brand":"Interwood Chair Patchwork","Name":"Chair Patchwork","Price":"PKR 15,355","Color":"Light Color, Natural",},
    {"id":9,"Image":"Assets/inerwood prod/if-dining1.jpg","Brand":"Interwood Deco Extendable","Name":"Deco Extendable","Price":"PKR 76,360","Color":"__",},
    {"id":10,"Image":"Assets/inerwood prod/if-dining3.jpg","Brand":"Interwood Willa","Name":"Willa","Price":"PKR 79,016","Color":"__",},
    {"id":11,"Image":"Assets/inerwood prod/if-decor1.jpg","Brand":"Interwood Bliss mirror","Name":"Bliss mirror","Price":"PKR 6,080","Color":"__",},
    {"id":12,"Image":"Assets/inerwood prod/if-decor2.jpg","Brand":"Interwood Milano clock","Name":"Milano clock","Price":"PKR 9,785","Color":"Golden&Black",},
    {"id":13,"Image":"Assets/habitt/h-bed1.webp","Brand":"Habitt Kenton X Bed","Name":"Kenton X","Price":"Rs.105,000","Color":"__",},
    {"id":14,"Image":"Assets/habitt/h-bed2.webp","Brand":"Habitt Carter Bed","Name":"Carter Bed","Price":"Rs.99,000","Color":"__",},
    {"id":15,"Image":"Assets/habitt/h-chair1.webp","Brand":"Habitt Round bac chair","Name":"Round bac chair","Price":"Rs.79,000","Color":"Ligh Brown",},
    {"id":16,"Image":"Assets/habitt/h-chair2.webp","Brand":"Habitt Vintage Chair","Name":"Vintage Chair","Price":"Rs.119,000","Color":"Dark Brown",},
    {"id":17,"Image":"Assets/habitt/h-sao2.webp","Brand":"Habitt Dynamic Table","Name":"Dynamic Table","Price":"Soon","Color":"__",},
    {"id":18,"Image":"Assets/habitt/h-sao6.webp","Brand":"Habitt Portable Workstation","Name":"Portable Workstation","Price":"Rs.22,900","Color":"__",},
    {"id":19,"Image":"Assets/habitt/h-sofa1.webp","Brand":"Habitt Osborne","Name":"Osborne 201","Price":"Rs.59,000","Color":"Pinkish",},
    {"id":20,"Image":"Assets/habitt/h-sofa3.webp","Brand":"Habitt Raven Sofa","Name":"Raven Sofa","Price":"Rs.34,000","Color":"Brown",},
    {"id":21,"Image":"Assets/habitt/h-decor1.webp","Brand":"Habitt T-light glass","Name":"T-light glass","Price":"Rs.1,290","Color":"Blue",},
]